### ISSUE TITLE
An error occurred when parsing the cuasm file into a cubin file

### ISSUE THREAD

**Issue by Liu-xiandong** [cloudcores/CuAssembler#6]
Hello, I am using CuAssembler's example.
```
__global__ void vectorAdd(const float* a, const float* b, float* c)
{
    int idx = threadIdx.x + blockIdx.x * blockDim.x;
    c[idx] = a[idx] + b[idx];
}
```
The previous steps are normal. But when I tried to convert the cuasm file to cubin file, I get an error, as follows:
```
2022-01-28 05:55:42,506 -          - Running CuAsmParser.parse...
2022-01-28 05:55:42,506 -    ENTRY -     Parsing file vecadd.sm_70.cuasm
2022-01-28 05:55:42,507 -          -     Running CuAsmParser.__preScan...
Traceback (most recent call last):
  File "asm2bin.py", line 6, in <module>
    cap.parse(asmname)
  File "/CuAssembler/CuAsm/CuAsmLogger.py", line 143, in wrapper
    ret = func(*args, **kwargs)
  File "CuAssembler/CuAsm/CuAsmParser.py", line 734, in parse
    self.__preScan()
  File "CuAssembler/CuAsm/CuAsmLogger.py", line 174, in wrapper
    ret = func(*args, **kwargs)
  File "CuAssembler/CuAsm/CuAsmParser.py", line 842, in __preScan
    self.__dirDict[cmd](args)
  File "CuAssembler/CuAsm/CuAsmParser.py", line 652, in <lambda>
    '.__elf_flags'            : (lambda args: self.__dir_elfheader('flags'           , args)),
  File "CuAssembler/CuAsm/CuAsmParser.py", line 1406, in __dir_elfheader
    self.__mCuInsAsmRepos.setToDefaultInsAsmDict()
  File "/CuAssembler/CuAsm/CuInsAssemblerRepos.py", line 38, in setToDefaultInsAsmDict
    fname = Config.getDefaultInsAsmReposFile(self.__mSMVersion.getVersionNumber())
  File "/CuAssembler/CuAsm/config.py", line 52, in getDefaultInsAsmReposFile
    raise IOError('File %s not found!' % repos_name)
OSError: File DefaultInsAsmRepos.sm_70.txt not found!
```

The software versions are as follows:
python 3.7
CUDA 11.2

GPU used is V100

How should this situation be resolved?

**Comment by Liu-xiandong** [comment]
sm_70(Volta) is not supported now.
